version: "3"
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - "./docker-compose/downloads:/home/seluser/Downloads"
    extra_hosts:
      - "docker-host:$HOST_IP"
