version: "3"
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900" # VNC
    extra_hosts:
      - "docker-host:$HOST_IP"
    environment:
      - "SE_OPTS=--enable-managed-downloads true"
